---
# tasks file for squid

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - squid

- name: Include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags:
    - squid

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - squid

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - squid

- name: Create Squid configuration file
  become: yes
  template:
    src: squid.conf.j2
    dest: "{{ squid_config_dir }}/squid.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Create Squid error page CSS file
  become: yes
  template:
    src: errorpage.css.j2
    dest: "{{ squid_config_dir }}/errorpage.css"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Create Squid basic auth users
  become: yes
  htpasswd:
    create: yes
    name: "{{ squid_username }}"
    password: "{{ squid_password }}"
    path: "/etc/squid3/passwords"
    state: present

- name: Disabling IPv6 – create sysctl file
  template: src=sysctl.conf dest=/etc/sysctl.conf owner=root group=bin mode=0644

- name: apply sysctl
  shell: sysctl -p

- name: Configure /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces

- name: Restart networking service
  service: name=networking state=restarted

- name: Ensure Squid service is started and enabled on boot
  become: yes
  service:
    name: "{{ squid_service_name }}"
    state: started
    enabled: yes
  tags:
    - squid
